{% set name = "oiffile" %}
{% set version = "2024.5.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oiffile-{{ version }}.tar.gz
  sha256: 7a57b8c5afbf1a536bbb2581ebab4daba7219a0ae654073bb285c308d988a8ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >=3.9
    - tifffile

test:
  imports:
    - oiffile
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/oiffile
  summary: Read Olympus(r) image files (OIF and OIB)
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/oiffile/

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
