{% set name = "oiffile" %}
{% set version = "2023.8.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oiffile-{{ version }}.tar.gz
  sha256: cb1baad8bceec1d950e8ee7245093af044f3e13d4a5ab930bae88a30a05b050c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - tifffile

test:
  imports:
    - oiffile
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/oiffile
  summary: Read Olympus(r) image files (OIF and OIB)
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/oiffile/

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
